### ISSUE TITLE
Consider using the `http` crate

### ISSUE THREAD

**Issue by LegNeato** [esp-rs/embedded-svc#55]
It seems that `embedded-svc`'s http service abstraction is not as mature or robust as the `http` crate. Is there any reason to not use the `http` crate directly?

**Comment by ivmarkov** [comment]
The `http` crate does not offer any service abstraction (traits). Please point these to me if I've missed them. What it offers instead are **concrete utility types** for stuff like headers, request parameters and so on. My take on these is that if you are implementing an HTTP server or client from scratch, you might consider utilizing those, but they would otherwise be a poor choice for abstracting an existing HTTP service *in the embedded space*, as they use allocations all over the place.

Last but not least, they are STD-only.

**Comment by LegNeato** [comment]
Sorry, I wasn't clear (and I'm not too familiar with this project or embedded so feel free to tell me to go away!

In this project's http mod, stuff like Headers, Method, and Status are defined. Those are also defined in http AFAIK, though I am not sure which require std. Additionally, in the http service definition of this crate many of the apis are "stringly" typed, which is usually a codesmell.
