### ISSUE TITLE
HttpServer trait?

### ISSUE THREAD

**Issue by zhangzqs** [esp-rs/embedded-svc#63]
I found http client in `embedded-svc` it's a Connection wrapper
https://github.com/esp-rs/embedded-svc/blob/ad0016b5e1d74d447c929a7cb78dc3ba358fc676/src/http/client.rs#L7-L11

But is there any http server trait?

reference to esp-idf-svc:
https://github.com/esp-rs/esp-idf-svc/blob/2191e60cb8b85fba5e64bd09a55028955d38792d/src/http/server.rs#L405-L412
https://github.com/esp-rs/esp-idf-svc/blob/2191e60cb8b85fba5e64bd09a55028955d38792d/src/http/server.rs#L438-L440

Maybe we can use trait code as follows?

```rust

pub trait Server<'a> {
    type Conn<'r>: Connection;
    type HttpServerError: std::error::Error;

    fn handler<H>(
        &mut self,
        uri: &str,
        method: Method,
        handler: H,
    ) -> Result<&mut Self, Self::HttpServerError>
    where
        H: for<'r> Handler<Self::Conn<'r>> + Send + 'a;

    fn fn_handler<F>(
        &mut self,
        uri: &str,
        method: Method,
        f: F,
    ) -> Result<&mut Self, Self::HttpServerError>
    where
        F: for<'r> Fn(Request<&mut Self::Conn<'r>>) -> HandlerResult + Send + 'a,
    {
        self.handler(uri, method, FnHandler::new(f))
    }
}
```

**Comment by ivmarkov** [comment]
Such a trait [used to be there long time ago](https://github.com/esp-rs/embedded-svc/blob/v0.22.3/src/http/server/registry.rs#L9).

I have removed it, because this trait is *impossible* to implement without using `alloc`. And you need alloc to turn the generic `H: Handler` handler into a `dyn Handler` instance, by potentially using boxing, as in `Box<dyn Handler>`.

Since `embedded-svc` strives to have all its traits implementable in `no_std` and without heap allocations, I therefore removed it in later versions. 

While this trait might be useful, its usage is very limited - as in it can only abstract the code that *registers* your handlers. Abstracting the handlers themselves is way more useful, as that way you can re-use them across many HTTP servers.
